# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-06-01T22:50:42+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Literal, Optional, TypeAlias, Union

PolyhookSchema: TypeAlias = Any


class CallerKind(Enum):
    claude_code = "claude-code"
    cursor = "cursor"
    windsurf = "windsurf"
    cline = "cline"
    amp = "amp"
    unknown = "unknown"


class Event(Enum):
    tool_before = "tool:before"
    tool_after = "tool:after"
    session_start = "session:start"
    session_stop = "session:stop"
    agent_stop = "agent:stop"
    notification = "notification"


@dataclass
class HookEvent:
    event: Event
    sessionId: str
    caller: CallerKind
    tool: Optional[str] = None
    input: Optional[dict[str, Any]] = None
    output: Optional[dict[str, Any]] = None
    agentId: Optional[str] = None


@dataclass
class ApproveResponse:
    action: Literal["approve"]


@dataclass
class BlockResponse:
    action: Literal["block"]
    message: str


@dataclass
class ModifyResponse:
    action: Literal["modify"]
    input: dict[str, Any]


HookResponse: TypeAlias = Union[ApproveResponse, BlockResponse, ModifyResponse]
