// Code generated by go-jsonschema from schema.json; DO NOT EDIT.

package polyhook

// ---------------------------------------------------------------------------
// CallerKind
// ---------------------------------------------------------------------------

// CallerKind identifies which AI coding agent invoked the hook binary.
// The value is the canonical lowercase slug used by each tool's hook runner.
type CallerKind = string

const (
	CallerClaudeCode CallerKind = "claude-code"
	CallerCursor     CallerKind = "cursor"
	CallerWindsurf   CallerKind = "windsurf"
	CallerCline      CallerKind = "cline"
	CallerAmp        CallerKind = "amp"
	CallerUnknown    CallerKind = "unknown"
)

// ---------------------------------------------------------------------------
// HookEvent
// ---------------------------------------------------------------------------

// HookEvent is the normalized event payload delivered to every hook handler
// after polyhook.wasm has parsed and translated the caller-specific stdin
// format.
type HookEvent struct {
	// Normalized event kind. One of: "tool:before" (about to run a tool),
	// "tool:after" (tool finished), "session:start" (new agent session opened),
	// "session:stop" (agent session closed), "agent:stop" (sub-agent returned),
	// "notification" (informational message, no response required).
	Event string `json:"event"`

	// Normalized tool name (e.g. "bash", "write_file", "read_file"). Present
	// for tool:before and tool:after events; null for all other event kinds.
	Tool *string `json:"tool,omitempty"`

	// Tool input arguments as a free-form object. Present for tool:before
	// events; null otherwise. The shape depends on the specific tool being called.
	Input map[string]interface{} `json:"input,omitempty"`

	// Tool output as a free-form object. Present for tool:after events; null
	// otherwise. The shape depends on the specific tool that produced the output.
	Output map[string]interface{} `json:"output,omitempty"`

	// Opaque session identifier provided by the calling AI tool. Used to
	// correlate events that belong to the same agent session.
	SessionID string `json:"sessionId"`

	// Opaque identifier for the sub-agent that triggered this event. Present
	// only when the hook is invoked from within a sub-agent context; null at
	// the top-level agent.
	AgentID *string `json:"agentId,omitempty"`

	// The AI coding tool that invoked this hook binary, detected from
	// environment variables and stdin format. Defaults to "unknown" when
	// detection fails.
	Caller CallerKind `json:"caller"`
}

// ---------------------------------------------------------------------------
// HookResponse discriminated union
// ---------------------------------------------------------------------------

// HookResponse is the sealed interface for hook responses. Construct values
// via Approve(), Block(), or Modify() — do not implement this interface
// directly. Discriminated on the "action" field.
type HookResponse interface {
	hookResponse()
}

// ApproveResponse instructs the AI tool to proceed with the operation
// unchanged. This is the default no-op response when a hook handler does not
// need to intervene.
type ApproveResponse struct {
	// Discriminator field identifying this as an approve response.
	Action string `json:"action"`
}

func (ApproveResponse) hookResponse() {}

// BlockResponse instructs the AI tool to abort the pending operation and
// surface the provided message to the user. The tool call is not executed.
type BlockResponse struct {
	// Discriminator field identifying this as a block response.
	Action string `json:"action"`

	// Human-readable explanation shown to the user explaining why the operation
	// was blocked. Should be clear and actionable.
	Message string `json:"message"`
}

func (BlockResponse) hookResponse() {}

// ModifyResponse instructs the AI tool to execute the operation with a
// modified input instead of the original. Useful for sanitising arguments or
// injecting safety constraints.
type ModifyResponse struct {
	// Discriminator field identifying this as a modify response.
	Action string `json:"action"`

	// Replacement input arguments to use instead of the original tool input.
	// The shape must be compatible with the tool being called.
	Input map[string]interface{} `json:"input"`
}

func (ModifyResponse) hookResponse() {}
