// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package polyhook

import "encoding/json"
import "fmt"
import "reflect"

// Instructs the AI tool to proceed with the operation unchanged. This is the
// default no-op response when a hook handler does not need to intervene.
type ApproveResponse struct {
	// Discriminator field identifying this as an approve response.
	Action string `json:"action" yaml:"action" mapstructure:"action"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApproveResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in ApproveResponse: required")
	}
	type Plain ApproveResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Action != "approve" {
		return fmt.Errorf("field %s: must be equal to %s", "action", "approve")
	}
	*j = ApproveResponse(plain)
	return nil
}

// Instructs the AI tool to abort the pending operation and surface the provided
// message to the user. The tool call is not executed.
type BlockResponse struct {
	// Discriminator field identifying this as a block response.
	Action string `json:"action" yaml:"action" mapstructure:"action"`

	// Human-readable explanation shown to the user explaining why the operation was
	// blocked. Should be clear and actionable.
	Message string `json:"message" yaml:"message" mapstructure:"message"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BlockResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in BlockResponse: required")
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in BlockResponse: required")
	}
	type Plain BlockResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Action != "block" {
		return fmt.Errorf("field %s: must be equal to %s", "action", "block")
	}
	*j = BlockResponse(plain)
	return nil
}

type CallerKind string

const CallerKindAmp CallerKind = "amp"
const CallerKindClaudeCode CallerKind = "claude-code"
const CallerKindCline CallerKind = "cline"
const CallerKindCursor CallerKind = "cursor"
const CallerKindGeminiCli CallerKind = "gemini-cli"
const CallerKindUnknown CallerKind = "unknown"
const CallerKindWindsurf CallerKind = "windsurf"

var enumValues_CallerKind = []interface{}{
	"claude-code",
	"cursor",
	"windsurf",
	"cline",
	"amp",
	"gemini-cli",
	"unknown",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CallerKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CallerKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CallerKind, v)
	}
	*j = CallerKind(v)
	return nil
}

// The normalized event payload delivered to every hook handler after polyhook.wasm
// has parsed and translated the caller-specific stdin format.
type HookEvent struct {
	// Opaque identifier for the sub-agent that triggered this event. Present only
	// when the hook is invoked from within a sub-agent context; null at the top-level
	// agent.
	AgentId HookEventAgentId `json:"agentId,omitempty,omitzero" yaml:"agentId,omitempty" mapstructure:"agentId,omitempty"`

	// The executable being invoked. Only present for bash tool events where
	// input.command is available. Extracted as the first non-env-assignment token of
	// the command string (e.g. 'git' from 'GIT_DIR=.git git commit'). Null for all
	// other tool kinds.
	Bin HookEventBin `json:"bin,omitempty,omitzero" yaml:"bin,omitempty" mapstructure:"bin,omitempty"`

	// The AI coding tool that invoked this hook binary, detected from environment
	// variables and stdin format. Defaults to 'unknown' when detection fails.
	Caller CallerKind `json:"caller" yaml:"caller" mapstructure:"caller"`

	// Normalized event kind. One of: 'tool:before' (about to run a tool),
	// 'tool:after' (tool finished), 'session:start' (new agent session opened),
	// 'session:stop' (agent session closed), 'agent:stop' (sub-agent returned),
	// 'notification' (informational message, no response required).
	Event HookEventEvent `json:"event" yaml:"event" mapstructure:"event"`

	// Tool input arguments as a free-form object. Present for tool:before events;
	// null otherwise. The shape depends on the specific tool being called.
	Input interface{} `json:"input,omitempty,omitzero" yaml:"input,omitempty" mapstructure:"input,omitempty"`

	// Tool output as a free-form object. Present for tool:after events; null
	// otherwise. The shape depends on the specific tool that produced the output.
	Output interface{} `json:"output,omitempty,omitzero" yaml:"output,omitempty" mapstructure:"output,omitempty"`

	// Opaque session identifier provided by the calling AI tool. Used to correlate
	// events that belong to the same agent session.
	SessionId string `json:"sessionId" yaml:"sessionId" mapstructure:"sessionId"`

	// Normalized tool name (e.g. 'bash', 'write_file', 'read_file'). Present for
	// tool:before and tool:after events; null for all other event kinds.
	Tool HookEventTool `json:"tool,omitempty,omitzero" yaml:"tool,omitempty" mapstructure:"tool,omitempty"`
}

// Opaque identifier for the sub-agent that triggered this event. Present only when
// the hook is invoked from within a sub-agent context; null at the top-level
// agent.
type HookEventAgentId *string

// The executable being invoked. Only present for bash tool events where
// input.command is available. Extracted as the first non-env-assignment token of
// the command string (e.g. 'git' from 'GIT_DIR=.git git commit'). Null for all
// other tool kinds.
type HookEventBin *string

type HookEventEvent string

const HookEventEventAgentStop HookEventEvent = "agent:stop"
const HookEventEventNotification HookEventEvent = "notification"
const HookEventEventSessionStart HookEventEvent = "session:start"
const HookEventEventSessionStop HookEventEvent = "session:stop"
const HookEventEventToolAfter HookEventEvent = "tool:after"
const HookEventEventToolBefore HookEventEvent = "tool:before"

var enumValues_HookEventEvent = []interface{}{
	"tool:before",
	"tool:after",
	"session:start",
	"session:stop",
	"agent:stop",
	"notification",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HookEventEvent) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_HookEventEvent {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_HookEventEvent, v)
	}
	*j = HookEventEvent(v)
	return nil
}

// Normalized tool name (e.g. 'bash', 'write_file', 'read_file'). Present for
// tool:before and tool:after events; null for all other event kinds.
type HookEventTool *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *HookEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["caller"]; raw != nil && !ok {
		return fmt.Errorf("field caller in HookEvent: required")
	}
	if _, ok := raw["event"]; raw != nil && !ok {
		return fmt.Errorf("field event in HookEvent: required")
	}
	if _, ok := raw["sessionId"]; raw != nil && !ok {
		return fmt.Errorf("field sessionId in HookEvent: required")
	}
	type Plain HookEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = HookEvent(plain)
	return nil
}

// The response a hook handler returns to polyhook.wasm, which translates it into
// the format expected by the detected caller. Discriminated on the 'action' field.
type HookResponse interface{}

// Instructs the AI tool to execute the operation with a modified input instead of
// the original. Useful for sanitising arguments or injecting safety constraints.
type ModifyResponse struct {
	// Discriminator field identifying this as a modify response.
	Action string `json:"action" yaml:"action" mapstructure:"action"`

	// Replacement input arguments to use instead of the original tool input. The
	// shape must be compatible with the tool being called.
	Input ModifyResponseInput `json:"input" yaml:"input" mapstructure:"input"`
}

// Replacement input arguments to use instead of the original tool input. The shape
// must be compatible with the tool being called.
type ModifyResponseInput map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ModifyResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in ModifyResponse: required")
	}
	if _, ok := raw["input"]; raw != nil && !ok {
		return fmt.Errorf("field input in ModifyResponse: required")
	}
	type Plain ModifyResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Action != "modify" {
		return fmt.Errorf("field %s: must be equal to %s", "action", "modify")
	}
	*j = ModifyResponse(plain)
	return nil
}
