// @generated — source: schema.json, generator: typify 0.6 via build.rs.
// Rebuilt automatically by `cargo build` whenever schema.json changes.
// Do not edit this file directly.
include!(concat!(env!("OUT_DIR"), "/types.rs"));
