// <auto-generated> Generated from schema.json — Run `make schema/dotnet` to regenerate. </auto-generated>
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Polyhook;

/// <summary>
/// The response a hook handler returns to polyhook.wasm, which translates it
/// into the format expected by the detected caller. Discriminated on the
/// 'action' field.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "action")]
[JsonDerivedType(typeof(ApproveResponse), typeDiscriminator: "approve")]
[JsonDerivedType(typeof(BlockResponse),   typeDiscriminator: "block")]
[JsonDerivedType(typeof(ModifyResponse),  typeDiscriminator: "modify")]
public abstract record HookResponse
{
    /// <summary>The discriminator value sent in the JSON payload.</summary>
    [JsonPropertyName("action")]
    public abstract string Action { get; }
}

/// <summary>
/// Instructs the AI tool to proceed with the operation unchanged.
/// This is the default no-op response when a hook handler does not need to intervene.
/// </summary>
public sealed record ApproveResponse : HookResponse
{
    /// <inheritdoc/>
    [JsonPropertyName("action")]
    public override string Action => "approve";
}

/// <summary>
/// Instructs the AI tool to abort the pending operation and surface the
/// provided message to the user. The tool call is not executed.
/// </summary>
public sealed record BlockResponse : HookResponse
{
    /// <inheritdoc/>
    [JsonPropertyName("action")]
    public override string Action => "block";

    /// <summary>
    /// Human-readable explanation shown to the user explaining why the
    /// operation was blocked. Should be clear and actionable.
    /// </summary>
    [JsonPropertyName("message")]
    public required string Message { get; init; }
}

/// <summary>
/// Instructs the AI tool to execute the operation with a modified input
/// instead of the original. Useful for sanitising arguments or injecting
/// safety constraints.
/// </summary>
public sealed record ModifyResponse : HookResponse
{
    /// <inheritdoc/>
    [JsonPropertyName("action")]
    public override string Action => "modify";

    /// <summary>
    /// Replacement input arguments to use instead of the original tool input.
    /// The shape must be compatible with the tool being called.
    /// </summary>
    [JsonPropertyName("input")]
    public required Dictionary<string, JsonElement> Input { get; init; }
}
