// <auto-generated> Generated from schema.json — Run `make schema/dotnet` to regenerate. </auto-generated>
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Polyhook;

/// <summary>
/// Identifies which AI coding agent invoked the hook binary.
/// The value is the canonical lowercase slug used by each tool's hook runner.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<CallerKind>))]
public enum CallerKind
{
    [JsonStringEnumMemberName("claude-code")]
    ClaudeCode,

    [JsonStringEnumMemberName("cursor")]
    Cursor,

    [JsonStringEnumMemberName("windsurf")]
    Windsurf,

    [JsonStringEnumMemberName("cline")]
    Cline,

    [JsonStringEnumMemberName("amp")]
    Amp,

    [JsonStringEnumMemberName("unknown")]
    Unknown,
}

/// <summary>
/// Normalized event kind delivered to every hook handler.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<EventKind>))]
public enum EventKind
{
    /// <summary>About to run a tool.</summary>
    [JsonStringEnumMemberName("tool:before")]
    ToolBefore,

    /// <summary>Tool finished.</summary>
    [JsonStringEnumMemberName("tool:after")]
    ToolAfter,

    /// <summary>New agent session opened.</summary>
    [JsonStringEnumMemberName("session:start")]
    SessionStart,

    /// <summary>Agent session closed.</summary>
    [JsonStringEnumMemberName("session:stop")]
    SessionStop,

    /// <summary>Sub-agent returned.</summary>
    [JsonStringEnumMemberName("agent:stop")]
    AgentStop,

    /// <summary>Informational message; no response required.</summary>
    [JsonStringEnumMemberName("notification")]
    Notification,
}

/// <summary>
/// The normalized event payload delivered to every hook handler after
/// polyhook.wasm has parsed and translated the caller-specific stdin format.
/// </summary>
public sealed record HookEvent
{
    /// <summary>
    /// Normalized event kind. One of: 'tool:before', 'tool:after',
    /// 'session:start', 'session:stop', 'agent:stop', 'notification'.
    /// </summary>
    [JsonPropertyName("event")]
    public required EventKind Event { get; init; }

    /// <summary>
    /// Normalized tool name (e.g. 'bash', 'write_file', 'read_file').
    /// Present for tool:before and tool:after events; null for all other event kinds.
    /// </summary>
    [JsonPropertyName("tool")]
    public string? Tool { get; init; }

    /// <summary>
    /// Tool input arguments as a free-form object. Present for tool:before
    /// events; null otherwise. The shape depends on the specific tool being called.
    /// </summary>
    [JsonPropertyName("input")]
    public Dictionary<string, JsonElement>? Input { get; init; }

    /// <summary>
    /// Tool output as a free-form object. Present for tool:after events;
    /// null otherwise. The shape depends on the specific tool that produced the output.
    /// </summary>
    [JsonPropertyName("output")]
    public Dictionary<string, JsonElement>? Output { get; init; }

    /// <summary>
    /// Opaque session identifier provided by the calling AI tool.
    /// Used to correlate events that belong to the same agent session.
    /// </summary>
    [JsonPropertyName("sessionId")]
    public required string SessionId { get; init; }

    /// <summary>
    /// Opaque identifier for the sub-agent that triggered this event.
    /// Present only when the hook is invoked from within a sub-agent context;
    /// null at the top-level agent.
    /// </summary>
    [JsonPropertyName("agentId")]
    public string? AgentId { get; init; }

    /// <summary>
    /// The AI coding tool that invoked this hook binary, detected from
    /// environment variables and stdin format. Defaults to 'unknown' when
    /// detection fails.
    /// </summary>
    [JsonPropertyName("caller")]
    public required CallerKind Caller { get; init; }
}
